### ISSUE TITLE
UI view dos not work when `experimentalSessionAndOrigin` flag is set to `true`

### ISSUE THREAD

**Issue by filiphric** [filiphric/cypress-plugin-api#4]
Apparently when `experimentalSessionAndOrigin` flag is enabled, there’s some other screen shown in the UI view. It informs the user that `about:blank` page was visited in between tests. For some reason the current state of the plugin is not able to handle it. Needs to be fixed as this may go to general availability soon and visiting empty page may become default behavior.

**Comment by estefafdez** [comment]
+1 on this one.

**Comment by leosuncin** [comment]
I can confirm, the UI doesn't show the requests but the tests do work. And I need `experimentalSessionAndOrigin` to be enabled because `next-auth` uses cookies

Reproduction repo: https://github.com/leosuncin/goal-app

**Comment by filiphric** [comment]
Fix released with #16

**Comment by leosuncin** [comment]
Hi @filiphric, it is still showing nothing

https://user-images.githubusercontent.com/4307697/195442518-ab226ef2-4e75-4bb1-92f9-8ab735ed30ce.mp4

**Comment by filiphric** [comment]
Can you please tell me which version of the plugin you are running?

**Comment by leosuncin** [comment]
> Can you please tell me which version of the plugin you are running?

cypress: 10.10.0
cypress-plugin-api: 1.3.0

**Comment by filiphric** [comment]
this will be a hard one to solve and it will require quite a bit of digging inside Cypress code. Somehow I need to tap in to the Cypress event that navigates to the `about:blank` page and tell it to not remove the code that I’m adding in the Cypress runner. I’ll create a separate issue for this.

Thank you for the reproduction repo, it helped a lot in understanding the problem!
